/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package birdpoint.telas;

import birdpoint.curso.Curso;
import birdpoint.curso.CursoDAO;
import birdpoint.curso.CursoTableModel;
import birdpoint.despesas.Despesas;
import birdpoint.despesas.DespesasDAO;
import birdpoint.despesas.DespesasTableModel;
import birdpoint.disciplina.Disciplina;
import birdpoint.disciplina.DisciplinaDAO;
import birdpoint.semestre.Semestre;
import birdpoint.semestre.SemestreDAO;
import birdpoint.semestre.SemestreTableModel;
import birdpoint.util.Util;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author AlexRamon
 */
public class CadastroDespesasCursos extends javax.swing.JDialog {

    Curso curso = new Curso();
    CursoDAO cursoDAO = new CursoDAO();

    Despesas despesa = new Despesas();
    DespesasDAO despesasDAO = new DespesasDAO();

    double totalDespesa;
    double resultado;

    SimpleDateFormat formatarData = new SimpleDateFormat("yyyy");
    Date dataAno;

    public CadastroDespesasCursos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btLimparActionPerformed(null);
        calcularResultado();
        preencherAnos();
    }

    public void preencherAnos() {
        dataAno = new Date();
        int anoAtual = Integer.parseInt(formatarData.format(dataAno));
        anoAtual--;
        for (int i = 0; i < 4; i++) {
            jcAno.addItem(anoAtual);
            anoAtual++;
        }
        anoAtual = Integer.parseInt(formatarData.format(dataAno));
        jcAno.setSelectedItem(anoAtual);
    }

    public void calcularResultado() {
        double somaDespesas = 0;
        try {
            somaDespesas += Double.parseDouble(tfSalarioCoor.getText());
            somaDespesas += Double.parseDouble(tfSalarioProf.getText());
            somaDespesas += Double.parseDouble(tfSalarioTecnic.getText());
            somaDespesas += Double.parseDouble(tfDespesasDeEncargos.getText());
            somaDespesas += Double.parseDouble(tfDespesasGerais.getText());
            somaDespesas += Double.parseDouble(tfDespesasOperacionais.getText());

            DecimalFormat df = new DecimalFormat("##.00");
            double resultadoTemp = (Double.parseDouble(tfReceita.getText()) - somaDespesas);
            totalDespesa = somaDespesas;
            resultado = resultadoTemp;
            tfDespesaTotal.setText(df.format(somaDespesas));
            tfResultado.setText(df.format(resultadoTemp));

            if (resultadoTemp < 0) {
                tfSituação.setText("Negativo");
                tfSituação.setForeground(new java.awt.Color(255, 51, 0));
                tfResultado.setForeground(new java.awt.Color(255, 51, 0));
            } else if (resultadoTemp > 0) {
                tfSituação.setText("Positivo");
                tfSituação.setForeground(new java.awt.Color(0, 153, 51));
                tfResultado.setForeground(new java.awt.Color(0, 153, 51));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfReceita = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        jlNome1 = new javax.swing.JLabel();
        jlNome2 = new javax.swing.JLabel();
        tfCurso = new javax.swing.JTextField();
        jLObrigatorioCurso = new javax.swing.JLabel();
        jLObrigatorioSemestre = new javax.swing.JLabel();
        btPesqusar1 = new javax.swing.JButton();
        jLObrigatorioCurso1 = new javax.swing.JLabel();
        tfDespesasGerais = new javax.swing.JTextField();
        jlNome3 = new javax.swing.JLabel();
        tfSalarioTecnic = new javax.swing.JTextField();
        jLObrigatorioCurso3 = new javax.swing.JLabel();
        jlNome4 = new javax.swing.JLabel();
        tfSalarioCoor = new javax.swing.JTextField();
        jLObrigatorioCurso2 = new javax.swing.JLabel();
        jlNome6 = new javax.swing.JLabel();
        jLObrigatorioCurso4 = new javax.swing.JLabel();
        jlNome5 = new javax.swing.JLabel();
        tfSituação = new javax.swing.JTextField();
        jLObrigatorioCurso5 = new javax.swing.JLabel();
        tfDespesasOperacionais = new javax.swing.JTextField();
        jlNome7 = new javax.swing.JLabel();
        jLObrigatorioCurso6 = new javax.swing.JLabel();
        jlNome8 = new javax.swing.JLabel();
        tfDespesasDeEncargos = new javax.swing.JTextField();
        jLObrigatorioCurso7 = new javax.swing.JLabel();
        jlNome9 = new javax.swing.JLabel();
        jlNome10 = new javax.swing.JLabel();
        jlNome11 = new javax.swing.JLabel();
        tfSalarioProf = new javax.swing.JTextField();
        tfDespesaTotal = new javax.swing.JTextField();
        tfResultado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcAno = new javax.swing.JComboBox();
        jcMes = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jlCadTitulacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 482));
        setMinimumSize(new java.awt.Dimension(600, 482));
        setUndecorated(true);
        getContentPane().setLayout(null);

        tfReceita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfReceita.setText("0");
        tfReceita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfReceita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfReceitaFocusLost(evt);
            }
        });
        tfReceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfReceitaKeyTyped(evt);
            }
        });
        getContentPane().add(tfReceita);
        tfReceita.setBounds(470, 110, 100, 30);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(20, 390, 90, 70);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/Salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(480, 390, 80, 70);

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setContentAreaFilled(false);
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir);
        btExcluir.setBounds(390, 390, 80, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(180, 390, 80, 70);

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btPesquisar.setText("Pesquisar");
        btPesquisar.setContentAreaFilled(false);
        btPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btPesquisar);
        btPesquisar.setBounds(280, 390, 100, 69);

        jlNome1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome1.setText("Receita.:");
        getContentPane().add(jlNome1);
        jlNome1.setBounds(400, 110, 70, 30);

        jlNome2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome2.setText("Curso.:");
        getContentPane().add(jlNome2);
        jlNome2.setBounds(20, 110, 60, 30);

        tfCurso.setEditable(false);
        tfCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfCurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfCurso.setEnabled(false);
        getContentPane().add(tfCurso);
        tfCurso.setBounds(80, 110, 290, 30);

        jLObrigatorioCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso.setText("*");
        getContentPane().add(jLObrigatorioCurso);
        jLObrigatorioCurso.setBounds(570, 90, 10, 50);

        jLObrigatorioSemestre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioSemestre.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioSemestre.setText("*");
        getContentPane().add(jLObrigatorioSemestre);
        jLObrigatorioSemestre.setBounds(370, 100, 10, 30);

        btPesqusar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesqusar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar20.png"))); // NOI18N
        btPesqusar1.setContentAreaFilled(false);
        btPesqusar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btPesqusar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesqusar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesqusar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesqusar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btPesqusar1);
        btPesqusar1.setBounds(370, 110, 30, 30);

        jLObrigatorioCurso1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso1.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso1.setText("*");
        getContentPane().add(jLObrigatorioCurso1);
        jLObrigatorioCurso1.setBounds(470, 180, 10, 50);

        tfDespesasGerais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDespesasGerais.setText("0");
        tfDespesasGerais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfDespesasGerais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDespesasGeraisFocusLost(evt);
            }
        });
        tfDespesasGerais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDespesasGeraisKeyTyped(evt);
            }
        });
        getContentPane().add(tfDespesasGerais);
        tfDespesasGerais.setBounds(380, 240, 90, 30);

        jlNome3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome3.setText("Despesas Gerais.:");
        getContentPane().add(jlNome3);
        jlNome3.setBounds(240, 240, 140, 30);

        tfSalarioTecnic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSalarioTecnic.setText("0");
        tfSalarioTecnic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfSalarioTecnic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSalarioTecnicFocusLost(evt);
            }
        });
        tfSalarioTecnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalarioTecnicKeyTyped(evt);
            }
        });
        getContentPane().add(tfSalarioTecnic);
        tfSalarioTecnic.setBounds(140, 240, 90, 30);

        jLObrigatorioCurso3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso3.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso3.setText("*");
        getContentPane().add(jLObrigatorioCurso3);
        jLObrigatorioCurso3.setBounds(630, 160, 10, 50);

        jlNome4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome4.setText("Salários Coor.:");
        getContentPane().add(jlNome4);
        jlNome4.setBounds(20, 200, 120, 30);

        tfSalarioCoor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSalarioCoor.setText("0");
        tfSalarioCoor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfSalarioCoor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSalarioCoorFocusLost(evt);
            }
        });
        tfSalarioCoor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalarioCoorKeyTyped(evt);
            }
        });
        getContentPane().add(tfSalarioCoor);
        tfSalarioCoor.setBounds(140, 200, 90, 30);

        jLObrigatorioCurso2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso2.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso2.setText("*");
        getContentPane().add(jLObrigatorioCurso2);
        jLObrigatorioCurso2.setBounds(230, 180, 10, 50);

        jlNome6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome6.setText("Situação");
        getContentPane().add(jlNome6);
        jlNome6.setBounds(420, 300, 70, 30);

        jLObrigatorioCurso4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso4.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso4.setText("*");
        getContentPane().add(jLObrigatorioCurso4);
        jLObrigatorioCurso4.setBounds(230, 220, 10, 50);

        jlNome5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome5.setText("Salários Prof.:");
        getContentPane().add(jlNome5);
        jlNome5.setBounds(20, 160, 110, 30);

        tfSituação.setEditable(false);
        tfSituação.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSituação.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        getContentPane().add(tfSituação);
        tfSituação.setBounds(400, 330, 110, 30);

        jLObrigatorioCurso5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso5.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso5.setText("*");
        getContentPane().add(jLObrigatorioCurso5);
        jLObrigatorioCurso5.setBounds(230, 140, 10, 50);

        tfDespesasOperacionais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDespesasOperacionais.setText("0");
        tfDespesasOperacionais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfDespesasOperacionais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDespesasOperacionaisFocusLost(evt);
            }
        });
        tfDespesasOperacionais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDespesasOperacionaisKeyTyped(evt);
            }
        });
        getContentPane().add(tfDespesasOperacionais);
        tfDespesasOperacionais.setBounds(380, 160, 90, 30);

        jlNome7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome7.setText("Despesas Operac.:");
        getContentPane().add(jlNome7);
        jlNome7.setBounds(240, 160, 190, 30);

        jLObrigatorioCurso6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso6.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso6.setText("*");
        getContentPane().add(jLObrigatorioCurso6);
        jLObrigatorioCurso6.setBounds(470, 140, 10, 50);

        jlNome8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome8.setText("Encargos.:");
        jlNome8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jlNome8FocusLost(evt);
            }
        });
        getContentPane().add(jlNome8);
        jlNome8.setBounds(240, 200, 90, 30);

        tfDespesasDeEncargos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDespesasDeEncargos.setText("0");
        tfDespesasDeEncargos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfDespesasDeEncargos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDespesasDeEncargosFocusLost(evt);
            }
        });
        tfDespesasDeEncargos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDespesasDeEncargosKeyTyped(evt);
            }
        });
        getContentPane().add(tfDespesasDeEncargos);
        tfDespesasDeEncargos.setBounds(380, 200, 90, 30);

        jLObrigatorioCurso7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioCurso7.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioCurso7.setText("*");
        getContentPane().add(jLObrigatorioCurso7);
        jLObrigatorioCurso7.setBounds(470, 220, 10, 50);

        jlNome9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome9.setText("Salários Tecn.:");
        getContentPane().add(jlNome9);
        jlNome9.setBounds(20, 240, 120, 30);

        jlNome10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome10.setText("Despesa Total");
        getContentPane().add(jlNome10);
        jlNome10.setBounds(120, 300, 120, 30);

        jlNome11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jlNome11.setText("Resultado");
        getContentPane().add(jlNome11);
        jlNome11.setBounds(280, 300, 80, 30);

        tfSalarioProf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfSalarioProf.setText("0");
        tfSalarioProf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        tfSalarioProf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfSalarioProfFocusLost(evt);
            }
        });
        tfSalarioProf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalarioProfKeyTyped(evt);
            }
        });
        getContentPane().add(tfSalarioProf);
        tfSalarioProf.setBounds(140, 160, 90, 30);

        tfDespesaTotal.setEditable(false);
        tfDespesaTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfDespesaTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        getContentPane().add(tfDespesaTotal);
        tfDespesaTotal.setBounds(120, 330, 110, 30);

        tfResultado.setEditable(false);
        tfResultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfResultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 121, 0), 1, true));
        getContentPane().add(tfResultado);
        tfResultado.setBounds(260, 330, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Ano Despesa.:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 70, 100, 30);

        jcAno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----" }));
        jcAno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        getContentPane().add(jcAno);
        jcAno.setBounds(120, 70, 90, 30);

        jcMes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jcMes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        getContentPane().add(jcMes);
        jcMes.setBounds(320, 70, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Mês Despesa.:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 70, 100, 30);

        jlCadTitulacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/cad de despesas por curso.jpg"))); // NOI18N
        jlCadTitulacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlCadTitulacao.setMaximumSize(new java.awt.Dimension(600, 482));
        jlCadTitulacao.setMinimumSize(new java.awt.Dimension(600, 482));
        jlCadTitulacao.setPreferredSize(new java.awt.Dimension(600, 482));
        getContentPane().add(jlCadTitulacao);
        jlCadTitulacao.setBounds(0, 0, 600, 482);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (Util.chkVazio(tfCurso.getText(), tfDespesaTotal.getText(), tfDespesasDeEncargos.getText(), tfDespesasGerais.getText(), tfDespesasOperacionais.getText(), tfReceita.getText(), tfResultado.getText(), tfSalarioCoor.getText(), tfSalarioProf.getText(), tfSalarioTecnic.getText(), String.valueOf(jcAno.getSelectedItem()), String.valueOf(jcMes.getSelectedItem()))) {
            despesa.setAnoDispesa(Integer.parseInt(String.valueOf(jcAno.getSelectedItem())));
            despesa.setMesDispesa(String.valueOf(jcMes.getSelectedItem()));
            despesa.setCurso(curso);
            despesa.setDespesasDeEncargos(Double.parseDouble(tfDespesasDeEncargos.getText()));
            despesa.setDespesasGerais(Double.parseDouble(tfDespesasGerais.getText()));
            despesa.setDespesasOperacionais(Double.parseDouble(tfDespesasOperacionais.getText()));
            despesa.setReceitaCurso(Double.parseDouble(tfReceita.getText()));
            despesa.setResultadoDespesa(resultado);
            despesa.setSalarioCoor(Double.parseDouble(tfSalarioCoor.getText()));
            despesa.setSalarioProf(Double.parseDouble(tfSalarioProf.getText()));
            despesa.setSalarioTecn(Double.parseDouble(tfSalarioTecnic.getText()));
            despesa.setTotalDespesa(totalDespesa);
            despesasDAO.salvar(despesa);
            btLimparActionPerformed(null);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed

        if (despesa.getIdDespesa() != 0) {
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja excluir a despesa do curso: " + despesa.getCurso().getNomeCurso()
                    + "?", "BirdPoint", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
                if (despesasDAO.remover(despesa)) {
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Não foi possível excluir a despesa do curso: " + despesa.getCurso().getNomeCurso(),
                            "Erro ao Excluir", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "A exclusão foi cancelada!");
            }

        }
        btLimparActionPerformed(null);

    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        btExcluir.setEnabled(false);
        jcAno.setEnabled(true);
        jcMes.setEnabled(true);
        btPesqusar1.setEnabled(true);
        tfSalarioCoor.setText("0");
        tfSalarioProf.setText("0");
        tfSalarioTecnic.setText("0");
        tfDespesasDeEncargos.setText("0");
        tfDespesasGerais.setText("0");
        tfDespesasOperacionais.setText("0");
        tfReceita.setText("0");
        curso = new Curso();
        despesa = new Despesas();
        calcularResultado();
        jcAno.removeAllItems();
        jcAno.addItem("-----");
        preencherAnos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if (curso.getIdCurso() != 0 && !String.valueOf(jcAno.getSelectedItem()).equals("-----")) {
            List<Despesas> lista;
            lista = (despesasDAO.checkExistseq("anoDispesa", jcAno.getSelectedItem()));
            List<Despesas> listaFiltrada = new ArrayList<>();
            for (Despesas despesaTemp : lista) {
                if (despesaTemp.getCurso().getIdCurso() == curso.getIdCurso()) {
                    listaFiltrada.add(despesaTemp);
                }
            }
            DespesasTableModel itm = new DespesasTableModel(listaFiltrada);
            Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Despesa");
            if (objetoRetorno != null) {
                despesa = despesasDAO.consultarObjetoId("idDespesa", objetoRetorno);
                curso = despesa.getCurso();
                tfCurso.setText(despesa.getCurso().getNomeCurso());
                tfDespesasDeEncargos.setText(String.valueOf(despesa.getDespesasDeEncargos()));
                tfDespesasGerais.setText(String.valueOf(despesa.getDespesasGerais()));
                tfDespesasOperacionais.setText(String.valueOf(despesa.getDespesasOperacionais()));
                tfReceita.setText(String.valueOf(despesa.getReceitaCurso()));
                tfSalarioCoor.setText(String.valueOf(despesa.getSalarioCoor()));
                tfSalarioProf.setText(String.valueOf(despesa.getSalarioProf()));
                tfSalarioTecnic.setText(String.valueOf(despesa.getSalarioTecn()));
                jcAno.setSelectedItem(despesa.getAnoDispesa());
                jcMes.setSelectedItem(despesa.getMesDispesa());
                jcAno.setEnabled(false);
                jcMes.setEnabled(false);
                btPesqusar1.setEnabled(false);
                calcularResultado();
                btExcluir.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Para efetuar a pesquisa, informe o Ano e Curso!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btPesqusar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesqusar1ActionPerformed
        List<Curso> lista;
        lista = (cursoDAO.listar());
        CursoTableModel itm = new CursoTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Curso");
        if (objetoRetorno != null) {
            curso = cursoDAO.consultarObjetoId("idCurso", objetoRetorno);
            tfCurso.setText(curso.getNomeCurso());
        }
    }//GEN-LAST:event_btPesqusar1ActionPerformed

    private void tfReceitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfReceitaKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == 46) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfReceita.getText().length() >= 12) {
            evt.consume();
        }
    }//GEN-LAST:event_tfReceitaKeyTyped

    private void tfSalarioProfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioProfKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == 46) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfSalarioProf.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSalarioProfKeyTyped

    private void tfSalarioCoorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioCoorKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == 46) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfSalarioCoor.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSalarioCoorKeyTyped

    private void tfSalarioTecnicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioTecnicKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == 46) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfSalarioTecnic.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSalarioTecnicKeyTyped

    private void tfDespesasOperacionaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDespesasOperacionaisKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == 46) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfDespesasOperacionais.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_tfDespesasOperacionaisKeyTyped

    private void tfDespesasDeEncargosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDespesasDeEncargosKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == 46) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfDespesasDeEncargos.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_tfDespesasDeEncargosKeyTyped

    private void tfDespesasGeraisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDespesasGeraisKeyTyped
        int ascii = evt.getKeyChar();
        if (!(ascii >= 48 && ascii <= 57) && !(ascii == 46) && !(ascii == evt.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfDespesasGerais.getText().length() >= 9) {
            evt.consume();
        }
    }//GEN-LAST:event_tfDespesasGeraisKeyTyped

    private void tfReceitaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfReceitaFocusLost
        if (tfReceita.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha este campo!", "Campo Obrigatório!", JOptionPane.ERROR_MESSAGE);
            tfReceita.requestFocus();
        } else {
            calcularResultado();
        }
    }//GEN-LAST:event_tfReceitaFocusLost

    private void tfSalarioProfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSalarioProfFocusLost
        if (tfSalarioProf.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha este campo!", "Campo Obrigatório!", JOptionPane.ERROR_MESSAGE);
            tfSalarioProf.requestFocus();
        } else {
            calcularResultado();
        }
    }//GEN-LAST:event_tfSalarioProfFocusLost

    private void tfSalarioCoorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSalarioCoorFocusLost
        if (tfSalarioCoor.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha este campo!", "Campo Obrigatório!", JOptionPane.ERROR_MESSAGE);
            tfSalarioCoor.requestFocus();
        } else {
            calcularResultado();
        }
    }//GEN-LAST:event_tfSalarioCoorFocusLost

    private void tfSalarioTecnicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfSalarioTecnicFocusLost
        if (tfSalarioTecnic.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha este campo!", "Campo Obrigatório!", JOptionPane.ERROR_MESSAGE);
            tfSalarioTecnic.requestFocus();
        } else {
            calcularResultado();
        }
    }//GEN-LAST:event_tfSalarioTecnicFocusLost

    private void tfDespesasOperacionaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDespesasOperacionaisFocusLost
        if (tfDespesasOperacionais.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha este campo!", "Campo Obrigatório!", JOptionPane.ERROR_MESSAGE);
            tfDespesasOperacionais.requestFocus();
        } else {
            calcularResultado();
        }
    }//GEN-LAST:event_tfDespesasOperacionaisFocusLost

    private void jlNome8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlNome8FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jlNome8FocusLost

    private void tfDespesasDeEncargosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDespesasDeEncargosFocusLost
        if (tfDespesasDeEncargos.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha este campo!", "Campo Obrigatório!", JOptionPane.ERROR_MESSAGE);
            tfDespesasDeEncargos.requestFocus();
        } else {
            calcularResultado();
        }
    }//GEN-LAST:event_tfDespesasDeEncargosFocusLost

    private void tfDespesasGeraisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDespesasGeraisFocusLost
        if (tfDespesasGerais.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha este campo!", "Campo Obrigatório!", JOptionPane.ERROR_MESSAGE);
            tfDespesasGerais.requestFocus();
        } else {
            calcularResultado();
        }
    }//GEN-LAST:event_tfDespesasGeraisFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDespesasCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDespesasCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDespesasCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDespesasCursos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroDespesasCursos dialog = new CadastroDespesasCursos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesqusar1;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLObrigatorioCurso;
    private javax.swing.JLabel jLObrigatorioCurso1;
    private javax.swing.JLabel jLObrigatorioCurso2;
    private javax.swing.JLabel jLObrigatorioCurso3;
    private javax.swing.JLabel jLObrigatorioCurso4;
    private javax.swing.JLabel jLObrigatorioCurso5;
    private javax.swing.JLabel jLObrigatorioCurso6;
    private javax.swing.JLabel jLObrigatorioCurso7;
    private javax.swing.JLabel jLObrigatorioSemestre;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jcAno;
    private javax.swing.JComboBox jcMes;
    private javax.swing.JLabel jlCadTitulacao;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlNome10;
    private javax.swing.JLabel jlNome11;
    private javax.swing.JLabel jlNome2;
    private javax.swing.JLabel jlNome3;
    private javax.swing.JLabel jlNome4;
    private javax.swing.JLabel jlNome5;
    private javax.swing.JLabel jlNome6;
    private javax.swing.JLabel jlNome7;
    private javax.swing.JLabel jlNome8;
    private javax.swing.JLabel jlNome9;
    private javax.swing.JTextField tfCurso;
    private javax.swing.JTextField tfDespesaTotal;
    private javax.swing.JTextField tfDespesasDeEncargos;
    private javax.swing.JTextField tfDespesasGerais;
    private javax.swing.JTextField tfDespesasOperacionais;
    private javax.swing.JTextField tfReceita;
    private javax.swing.JTextField tfResultado;
    private javax.swing.JTextField tfSalarioCoor;
    private javax.swing.JTextField tfSalarioProf;
    private javax.swing.JTextField tfSalarioTecnic;
    private javax.swing.JTextField tfSituação;
    // End of variables declaration//GEN-END:variables
}
