/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package birdpoint.telas;

import birdpoint.professor.Professor;
import birdpoint.professor.ProfessorDAO;
import birdpoint.professor.ProfessorTableModel;
import birdpoint.util.LeitorBiometrico;
import birdpoint.util.Util;
import com.digitalpersona.onetouch.DPFPTemplate;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Adriano Lima
 */
public class CadastroDigital extends javax.swing.JDialog {

    Professor professor = new Professor();
    ProfessorDAO professorDAO = new ProfessorDAO();

    LeitorBiometrico digital = new LeitorBiometrico();

    //Variável pra armazenar os templates de digital
    DPFPTemplate templateDigital;

    public CadastroDigital(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btLimparActionPerformed(null);
    }

    private void capturarDigitalMaoDireita() {
        if(jlMaoDireita.getText().equals("Capturada!")){
            jlMaoDireita.setText("Não Capturada");
        }
        DPFPTemplate temp = digital.getTemplate(null, 1);
        byte[] b;
        try {
            b = temp.serialize();
            professor.setDigitalDireita(b);
            jlMaoDireita.setText("Capturada!");
        } catch (Exception e) {
        }
    }

    private void capturarDigitalMaoEsquerda() {
        if(jlMaoEsquerda.getText().equals("Capturada!")){
            jlMaoEsquerda.setText("Não Capturada");
        }
        DPFPTemplate temp = digital.getTemplate(null, 1);
        byte[] b;
        try {
            b = temp.serialize();
            professor.setDigitalEsquerda(b);
            jlMaoEsquerda.setText("Capturada!");
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        selecionarFoto = new javax.swing.JFileChooser();
        jlMaoDireita = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        tfNome = new javax.swing.JTextField();
        jLObrigatorioNome = new javax.swing.JLabel();
        btFoto = new javax.swing.JButton();
        btAdd21 = new javax.swing.JButton();
        btMaoDireita = new javax.swing.JButton();
        btMaoEsquerda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlMaoEsquerda = new javax.swing.JLabel();
        jlCadProfessores = new javax.swing.JLabel();

        selecionarFoto.setMaximumSize(new java.awt.Dimension(580, 245));
        selecionarFoto.setMinimumSize(new java.awt.Dimension(550, 245));
        selecionarFoto.setPreferredSize(new java.awt.Dimension(520, 320));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 421));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jlMaoDireita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlMaoDireita.setForeground(new java.awt.Color(255, 51, 0));
        jlMaoDireita.setText("Não Capturada");
        getContentPane().add(jlMaoDireita);
        jlMaoDireita.setBounds(410, 270, 120, 20);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/voltar.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.setContentAreaFilled(false);
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(20, 340, 90, 70);

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/limpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar);
        btLimpar.setBounds(220, 340, 80, 70);

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/Salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar);
        btSalvar.setBounds(480, 340, 80, 70);

        tfNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tfNome);
        tfNome.setBounds(200, 100, 350, 23);

        jLObrigatorioNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLObrigatorioNome.setForeground(new java.awt.Color(204, 0, 0));
        jLObrigatorioNome.setText("*");
        getContentPane().add(jLObrigatorioNome);
        jLObrigatorioNome.setBounds(550, 90, 9, 30);

        btFoto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btFoto.setContentAreaFilled(false);
        btFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btFoto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btFoto);
        btFoto.setBounds(20, 90, 120, 140);

        btAdd21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar20.png"))); // NOI18N
        btAdd21.setContentAreaFilled(false);
        btAdd21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAdd21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdd21ActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd21);
        btAdd21.setBounds(550, 100, 40, 20);

        btMaoDireita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMaoDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btMaoDireita.setText("Digital Mão Direita");
        btMaoDireita.setContentAreaFilled(false);
        btMaoDireita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMaoDireita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMaoDireita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMaoDireita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaoDireitaActionPerformed(evt);
            }
        });
        getContentPane().add(btMaoDireita);
        btMaoDireita.setBounds(370, 180, 190, 69);

        btMaoEsquerda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMaoEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/pesquisar.png"))); // NOI18N
        btMaoEsquerda.setText("Digital Mão Esquerda");
        btMaoEsquerda.setContentAreaFilled(false);
        btMaoEsquerda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMaoEsquerda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMaoEsquerda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMaoEsquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaoEsquerdaActionPerformed(evt);
            }
        });
        getContentPane().add(btMaoEsquerda);
        btMaoEsquerda.setBounds(200, 180, 190, 69);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 100, 60, 20);

        jlMaoEsquerda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlMaoEsquerda.setForeground(new java.awt.Color(255, 51, 0));
        jlMaoEsquerda.setText("Não Capturada");
        getContentPane().add(jlMaoEsquerda);
        jlMaoEsquerda.setBounds(240, 270, 120, 20);

        jlCadProfessores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/birdpoint/imagens/cadProfessor.png"))); // NOI18N
        jlCadProfessores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jlCadProfessores);
        jlCadProfessores.setBounds(0, 0, 600, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        Util.limparCamposGenerico(this);
        professor = new Professor();
        tfNome.setEnabled(false);
        jlMaoDireita.setText("Não capturada!");
        jlMaoEsquerda.setText("Não capturada!");
        btMaoDireita.setEnabled(false);
        btMaoEsquerda.setEnabled(false);
        btFoto.setIcon(new ImageIcon(getClass().getResource("/birdpoint/imagens/default.jpg")));
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (Util.chkVazio(tfNome.getText())) {
            professorDAO.salvar(professor);
            btLimparActionPerformed(null);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void btFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFotoActionPerformed

    }//GEN-LAST:event_btFotoActionPerformed

    private void btAdd21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdd21ActionPerformed
        List<Professor> lista;
        lista = (professorDAO.listar());
        ProfessorTableModel itm = new ProfessorTableModel(lista);
        Object objetoRetorno = PesquisaGenerica.exibeTela(itm, "Professor");
        if (objetoRetorno != null) {
            professor = professorDAO.consultarObjetoId("idProfessor", objetoRetorno);
            tfNome.setText(professor.getNomeProfessor());
            try {
                ImageIcon foto = new ImageIcon();
                foto.setImage(Util.byteToImage(professor.getFotoProf()));
                btFoto.setIcon(foto);
            } catch (Exception e) {
            }
        }
        btMaoDireita.setEnabled(true);
        btMaoEsquerda.setEnabled(true);
    }//GEN-LAST:event_btAdd21ActionPerformed

    private void btMaoDireitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaoDireitaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Peça que por gentileza o professor(a) " + tfNome.getText() + "\n\n Escolha um dedo da mão DIREITA que ele gostaria de cadastrar\n\n"
                + "Após a escolha dele clique no OK abaixo para continuar o cadastro da digital");
        capturarDigitalMaoDireita();
    }//GEN-LAST:event_btMaoDireitaActionPerformed

    private void btMaoEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaoEsquerdaActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Peça que por gentileza o professor(a) " + tfNome.getText() + "\n\n Escolha um dedo da mão ESQUERDA que ele gostaria de cadastrar\n\n"
                + "Após a escolha dele clique no OK abaixo para continuar o cadastro da digital");
        capturarDigitalMaoEsquerda();
    }//GEN-LAST:event_btMaoEsquerdaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDigital.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDigital.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDigital.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDigital.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroDigital dialog = new CadastroDigital(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd21;
    private javax.swing.JButton btFoto;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btMaoDireita;
    private javax.swing.JButton btMaoEsquerda;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLObrigatorioNome;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlCadProfessores;
    private javax.swing.JLabel jlMaoDireita;
    private javax.swing.JLabel jlMaoEsquerda;
    private javax.swing.JFileChooser selecionarFoto;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
